name: ci

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Cypress dependencies
        run: |
          sudo apt -y update
          sudo apt -y install libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb

      - name: Install root dependencies
        run: npm ci

      - name: Run dependency check
        run: npm run dependencyCheck

      - name: Run all tests
        run: npm test

      - name: Run prebuild checks
        run: |
          npm run docu
          node build/checkTranslationKeys.mjs

      - name: Build client
        working-directory: client
        env:
          VITE_PUBLIC_POSTHOG_KEY: ${{ vars.VITE_PUBLIC_POSTHOG_KEY }}
          VITE_PUBLIC_POSTHOG_HOST: ${{ vars.VITE_PUBLIC_POSTHOG_HOST }}
        run: |
          npm ci
          npm run build

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Get git info
        id: git-info
        run: |
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "tags=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          echo "Building docker image for commit ${{ steps.git-info.outputs.hash }} on branch ${{ steps.git-info.outputs.branch }}"
          docker build -t poinz .

      - name: Test Docker image
        working-directory: poinz-e2e
        run: |
          docker run -e NODE_ENV=test -p9000:3000 --rm -d -ti poinz
          npm ci
          npm run test:e2e